version: "3.3"
services:
  pg-db1:
    image: postgres:latest
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: "dev_only_pwd"
      POSTGRES_DB: "slowpocket"
    volumes:
      - local_data:/var/lib/postgresql/data

volumes:
  local_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/slowpocket_data
